#ifndef STM32F_OLD_STD_PERIPHERAL_LIB_SUPPORT_H
#define STM32F_OLD_STD_PERIPHERAL_LIB_SUPPORT_H

#ifndef FLASH_FLAG_BANK1_BSY
#define FLASH_FLAG_BANK1_BSY FLASH_FLAG_BSY
#endif

#ifndef FLASH_FLAG_BANK1_PGERR
#define FLASH_FLAG_BANK1_PGERR FLASH_FLAG_PGERR
#endif

#ifndef FLASH_FLAG_BANK1_WRPRTERR
#define FLASH_FLAG_BANK1_WRPRTERR FLASH_FLAG_WRPRTERR
#endif

#ifndef FLASH_FLAG_BANK1_BSY
#define FLASH_FLAG_BANK1_BSY FLASH_FLAG_BSY
#endif


#endif //STM32F_OLD_STD_PERIPHERAL_LIB_SUPPORT_H
